CREATE TABLE event
(
id                INTEGER NOT NULL PRIMARY KEY,
code              VARCHAR(20),
parent_id         INTEGER,
project_id        INTEGER,
type_dict_id      INTEGER,
status_dict_id    INTEGER,
summary           VARCHAR(80),
remark            VARCHAR(80),
owner_id          INTEGER,
contact_id        INTEGER,
appl_dict_id      INTEGER,
package_id        INTEGER,
segment_id        INTEGER,
impact_dict_id    INTEGER,
priority_dict_id  INTEGER,
severity_dict_id  INTEGER,
notified_f        TINYINT NOT NULL DEFAULT '0',
blocking_f        TINYINT NOT NULL DEFAULT '0',
prod_f            TINYINT NOT NULL DEFAULT '0',
followed_f        TINYINT NOT NULL DEFAULT '0',
progress_t        TINYINT,
planif_package_id INTEGER,
asked_d           DATETIME,
planif_d          DATETIME,
opened_d          DATETIME,
logged_d          DATETIME,
closed_d          DATETIME,
last_user_id      INTEGER,
last_modif_d      DATETIME,
CHECK             (parent_id != id),
CHECK             (project_id != id)
);
